title = "anniespeaks"
baseURL = "https://blog.anniespeaks.com"
theme = "bilberry-hugo-theme"

enableRobotsTXT = true

# Change to your content language. Supported values: en, de, es, fr, ru
DefaultContentLanguage = "en"

# Enable / Disable Google Analytics statistics for your site
googleAnalytics = ""

# Enable / Disable comments on the articles via Disqus.
disqusShortname = "bilberry-hugo-theme"

[params]
  # Favicon for the browser's favorites and tabs
  favicon = "" # set a favicon icon

  # Custom CSS / JS modules that will be imported by the template.
  # Files are relative to the static/ directory or a URL.
  # Files are imported in the order they appear here, after
  # theme.css and theme.js, respectively.
  css_modules = []
  js_modules = []

  # Description and meta data for the search engines
  author = "Annie Wylie"
  description = "All things Annie"
  keywords = "annie,sydney,burlesque,party weird,dating"

  # How many articles should be displayed at once?
  paginate = 7

  # Enable / Disable MathJax
  enable_mathjax    = false

  # Enable / Disable algolia search
  algolia_search    = false
  # algolia_appId     = "Y2C4RWMPXW"
  # algolia_apiKey    = "50ea7f8c41c0ad233926e0be2b769ed1"
  # algolia_indexName = "default-content"

  # Header configuration
    # your subtitle if you want to use any
    subtitle = "Baby did a bad bad thing"

    # if you want to use gravatar for the header image
    gravatarEMail = ""

    # set an path to the image file you want to use | overwrites gravatar
    customImage = "/images/profile-fan.png"

    # always display the top navigation (with pages and search) on non-mobile screens
    permanentTopNav = true

  # social media profile urls for the footer links
  facebook   = "https://www.facebook.com/annie42"
  twitter    = ""
  googleplus = ""
  pinterest  = ""
  instagram  = "https://www.instagram.com/anniewylie"
  tumblr     = ""
  youtube    = ""
  vimeo      = ""
  github     = ""

# don't change anything here
[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"

[outputs]
  home = [ "HTML", "JSON" ]
  page = [ "HTML" ]
